FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --prod --output-path=www

FROM nginx:stable-alpine
COPY --from=builder /app/www /usr/share/nginx/html
EXPOSE 80
